In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [34]:
# x = np.arange(4*5, 4*(27+5), 2).reshape((9, 6))

df = np.random.randint(0, 200, (3, 2))
df

array([[  6,   8],
       [ 23, 148],
       [ 44, 119]])

In [26]:
df.T

array([[ 72,  15,  45,  84, 173,  62],
       [166,  98, 176, 172,   3,  53],
       [126, 169, 163, 195, 111, 183],
       [ 37,   4,  48,   1,   9, 188],
       [  8,  84,  18,  64,  21,  92],
       [ 44,  82,  60,  53,  69, 181],
       [ 69,  52, 152,  77,  29, 164],
       [ 22,  62,  76, 117,  51,  35],
       [170, 128, 153,  18,  88,  79]])

In [28]:
sort_by_cols = df.transpose()
x = np.delete(sort_by_cols, 2, 0)
y = sort_by_cols[2]

In [30]:
# Add a column of 1s for the intercept
x_b = np.c_[np.ones((x.shape[0], 1)), x]

# Compute beta_hat = (X^T X)^(-1) X^T y
beta_hat = np.linalg.inv(x_b.T @ x_b) @ (x_b.T @ y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 8)

In [20]:
x_b

array([[  1., 127.,  32.],
       [  1., 117., 142.]])

In [22]:
beta_hat

array([27.81054688, -0.13575745,  0.1011219 ])

In [ ]:
eq = beta_hat[0] + beta_hat[1]*x[0] + beta_hat[2]*x[1]

plt.style.use('_mpl-gallery')

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
ax.scatter(x[0], y)
ax.scatter(x[1], y)
ax.plot(x[0], x[1], eq)

ax.set(xticklabels=[],
       yticklabels=[],
       zticklabels=[])

plt.show()

In [ ]:
# y = mx + c

sort_by_cols = df.transpose()
x = sort_by_cols[0]
y = sort_by_cols[1]

x_avg = x.mean()
y_avg = y.mean()

m_num = 0
for x_i, y_i in df:
    m_num += (x_i - x_avg)*(y_i - y_avg)

m_den = 0
for x_i in x:
    m_den += (x_i - x_avg)**2

m = m_num / m_den
m

In [ ]:
c = y_avg - m*x_avg
c